"""Takes care of the communication with the MongoDB database."""

import ast
from typing import Any

import pandas as pd
from pymongo import MongoClient

from src.api.login_objects import MongoLogin


class DataBase:
    """
    Represents an object which communicates with a MongoDB database.

    attributes:
        conn:       Connection instance to communicate with a MongoDB database
        collection: Selection of a specific collection
    """

    def __init__(self, login: MongoLogin):
        """Inits the Database object."""

        client = MongoClient(login.host)
        self.conn = client[login.db]
        self.collection = login.collection

    def get_data(self, atts: list, limit: int) -> pd.DataFrame:
        """
        Extracts data from the database based on arguments which specifies the query.

        :param atts:        Attributes as search terms
        :param limit:       Number of entries in the resulting dataframe
        :return:            Pandas DataFrame as result
        """

        projection = {}
        if atts:
            projection = {att: 1 for att in atts}

        # Getting rid of the objectIDs generated by mongo
        projection['_id'] = 0

        try:

            coll = self.conn[self.collection]

            # Daten abfragen
            cursor = coll.find({}, projection)
            cursor = cursor.limit(limit)

            # Umwandeln der Cursor-Daten in eine Liste von Dictionaries
            data = list(cursor)

            # Erstellen eines DataFrames
            df = pd.DataFrame(data)
        except Exception as e:
            print(e)
            df = pd.DataFrame()

        return df

    def get_data_from_query(self, query: str | dict, **kwargs: Any) -> pd.DataFrame:
        """
        Extracts data from the database based on a query.

        :param query:   Query for extracting data from the database, this can be
            a string for everything or a dict for MongoDB
        :param kwargs:  Additional Arguments to specify the query,
            actually 'limit' is supported for MongoDB
        :return:        Pandas DataFrame as result
        """

        if isinstance(query, str):
            query = ast.literal_eval(query)

        try:
            coll = self.conn[self.collection]
            cursor = coll.find({}, query)

            if "limit" in kwargs:
                cursor = cursor.limit(kwargs['limit'])

            data = list(cursor)

            df = pd.DataFrame(data)

        except Exception as e:
            print(e)
            df = pd.DataFrame()

        return df
